name: Speedtest

on:
  workflow_run:
    workflows: ["Release"]
    types: [completed]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package-manager: [npm, pnpm, yarn, bun]
    steps:
      - uses: actions/checkout@v4

      - run: docker compose run --rm ${{ matrix.package-manager }}
